import type { Investment, Property } from "./types";

/**
 * Fallback content shown when the backend API is unreachable (e.g. during
 * local frontend-only development or before the database has been seeded).
 * The shape mirrors exactly what GET /api/v1/properties returns, so this
 * file becomes dead code the moment a real API is live — nothing else needs
 * to change.
 */
export const MOCK_PROPERTIES: Property[] = [
  {
    id: "mock-1",
    title: "Luxury 5 Bedroom Duplex, Maitama",
    slug: "luxury-5-bedroom-duplex-maitama",
    description:
      "An architectural masterpiece in the heart of Maitama featuring a private cinema, rooftop lounge, smart home automation, and panoramic views of Abuja's diplomatic district.",
    price: 850000000,
    currency: "NGN",
    address: "12 Aso Drive, Maitama",
    city: "Abuja",
    country: "Nigeria",
    latitude: 9.0967,
    longitude: 7.4951,
    property_type: "duplex",
    purpose: "buy",
    bedrooms: 5,
    bathrooms: 6,
    square_meters: 680,
    furnished: true,
    parking: true,
    security: true,
    swimming_pool: true,
    amenities: ["Smart Home", "Cinema Room", "Rooftop Lounge", "Solar Backup", "Gym"],
    video_urls: [],
    verification_status: "premium_verified",
    available: true,
    agent_id: "agent-1",
    agent: {
      id: "agent-1",
      user_id: "user-1",
      user: { id: "user-1", name: "Amara Johnson", avatar_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&q=80" },
      experience_years: 9,
      agency_name: "TheVHomes Elite",
      verified: true,
      verification_level: "premium_verified",
      rating: 4.9,
      reviews_count: 58,
    },
    images: [
      { id: "img-1", url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80", is_primary: true },
      { id: "img-2", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", is_primary: false },
      { id: "img-3", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80", is_primary: false },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    title: "Modern 3 Bedroom Apartment, Banana Island",
    slug: "modern-3-bedroom-apartment-banana-island",
    description:
      "Waterfront living redefined — a fully serviced apartment with concierge, infinity pool, and direct marina access on Lagos' most exclusive island.",
    price: 620000000,
    currency: "NGN",
    address: "9 Ocean Parade, Banana Island",
    city: "Lagos",
    country: "Nigeria",
    latitude: 6.4383,
    longitude: 3.4499,
    property_type: "apartment",
    purpose: "buy",
    bedrooms: 3,
    bathrooms: 4,
    square_meters: 310,
    furnished: true,
    parking: true,
    security: true,
    swimming_pool: true,
    amenities: ["Concierge", "Marina Access", "Infinity Pool", "Gym", "Kids Play Area"],
    video_urls: [],
    verification_status: "verified",
    available: true,
    agent_id: "agent-2",
    agent: {
      id: "agent-2",
      user_id: "user-2",
      user: { id: "user-2", name: "David Okafor", avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80" },
      experience_years: 6,
      agency_name: "TheVHomes Lagos",
      verified: true,
      verification_level: "verified",
      rating: 4.7,
      reviews_count: 31,
    },
    images: [
      { id: "img-4", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80", is_primary: true },
      { id: "img-5", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80", is_primary: false },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    title: "Serviced 2 Bedroom Shortlet, Wuse II",
    slug: "serviced-2-bedroom-shortlet-wuse-ii",
    description:
      "A designer-furnished shortlet apartment steps away from Abuja's business district — ideal for executive stays, complete with daily housekeeping.",
    price: 180000,
    currency: "NGN",
    address: "4 Aminu Kano Crescent, Wuse II",
    city: "Abuja",
    country: "Nigeria",
    latitude: 9.0765,
    longitude: 7.4834,
    property_type: "shortlet",
    purpose: "shortlet",
    bedrooms: 2,
    bathrooms: 2,
    square_meters: 140,
    furnished: true,
    parking: true,
    security: true,
    swimming_pool: false,
    amenities: ["Housekeeping", "Fast Wi-Fi", "Backup Power", "Netflix"],
    video_urls: [],
    verification_status: "verified",
    available: true,
    agent_id: "agent-1",
    agent: {
      id: "agent-1",
      user_id: "user-1",
      user: { id: "user-1", name: "Amara Johnson", avatar_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&q=80" },
      experience_years: 9,
      agency_name: "TheVHomes Elite",
      verified: true,
      verification_level: "premium_verified",
      rating: 4.9,
      reviews_count: 58,
    },
    images: [
      { id: "img-6", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80", is_primary: true },
      { id: "img-7", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80", is_primary: false },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    title: "Prime Commercial Land, Guzape",
    slug: "prime-commercial-land-guzape",
    description:
      "2,000 sqm of C-of-O titled land in fast-appreciating Guzape District, perfectly suited for a boutique hotel or luxury residential development.",
    price: 320000000,
    currency: "NGN",
    address: "Plot 45, Guzape District",
    city: "Abuja",
    country: "Nigeria",
    latitude: 9.0392,
    longitude: 7.5209,
    property_type: "land",
    purpose: "invest",
    bedrooms: 0,
    bathrooms: 0,
    square_meters: 2000,
    furnished: false,
    parking: false,
    security: true,
    swimming_pool: false,
    amenities: ["C of O", "Fenced", "Corner Piece"],
    video_urls: [],
    verification_status: "verified",
    available: true,
    agent_id: "agent-3",
    agent: {
      id: "agent-3",
      user_id: "user-3",
      user: { id: "user-3", name: "Fatima Bello", avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80" },
      experience_years: 12,
      agency_name: "TheVHomes Land Division",
      verified: true,
      verification_level: "verified",
      rating: 4.8,
      reviews_count: 44,
    },
    images: [
      { id: "img-8", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80", is_primary: true },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-5",
    title: "Boutique Hotel, Victoria Island",
    slug: "boutique-hotel-victoria-island",
    description:
      "A fully operational 24-room boutique hotel asset with strong occupancy history, rooftop bar, and event space — a turn-key investment opportunity.",
    price: 2100000000,
    currency: "NGN",
    address: "18 Ozumba Mbadiwe Ave, Victoria Island",
    city: "Lagos",
    country: "Nigeria",
    latitude: 6.4281,
    longitude: 3.4219,
    property_type: "hotel",
    purpose: "invest",
    bedrooms: 24,
    bathrooms: 26,
    square_meters: 1450,
    furnished: true,
    parking: true,
    security: true,
    swimming_pool: true,
    amenities: ["Rooftop Bar", "Event Hall", "Generator Suite", "CCTV"],
    video_urls: [],
    verification_status: "premium_verified",
    available: true,
    agent_id: "agent-2",
    agent: {
      id: "agent-2",
      user_id: "user-2",
      user: { id: "user-2", name: "David Okafor", avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80" },
      experience_years: 6,
      agency_name: "TheVHomes Lagos",
      verified: true,
      verification_level: "verified",
      rating: 4.7,
      reviews_count: 31,
    },
    images: [
      { id: "img-9", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80", is_primary: true },
      { id: "img-10", url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80", is_primary: false },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-6",
    title: "Contemporary Villa with Pool, Dubai Hills",
    slug: "contemporary-villa-pool-dubai-hills",
    description:
      "A six-bedroom contemporary villa overlooking the Dubai Hills golf course, with private pool, home theatre, and staff quarters.",
    price: 4200000,
    currency: "USD",
    address: "Golf Place, Dubai Hills Estate",
    city: "Dubai",
    country: "United Arab Emirates",
    latitude: 25.1109,
    longitude: 55.2422,
    property_type: "villa",
    purpose: "buy",
    bedrooms: 6,
    bathrooms: 7,
    square_meters: 920,
    furnished: false,
    parking: true,
    security: true,
    swimming_pool: true,
    amenities: ["Golf Course View", "Home Theatre", "Staff Quarters", "Smart Home"],
    video_urls: [],
    verification_status: "premium_verified",
    available: true,
    agent_id: "agent-4",
    agent: {
      id: "agent-4",
      user_id: "user-4",
      user: { id: "user-4", name: "Layla Haddad", avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80" },
      experience_years: 10,
      agency_name: "TheVHomes International",
      verified: true,
      verification_level: "premium_verified",
      rating: 5.0,
      reviews_count: 22,
    },
    images: [
      { id: "img-11", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80", is_primary: true },
      { id: "img-12", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80", is_primary: false },
    ],
    created_at: new Date().toISOString(),
  },
];

export const MOCK_INVESTMENTS: Investment[] = [
  {
    id: "inv-1",
    title: "Vhomes Gardens — Phase II, Guzape",
    description:
      "120-unit luxury apartment development with a projected 28% ROI over 24 months. Early investors receive priority unit allocation.",
    image_url: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1200&q=80",
    roi_estimate_percent: 28,
    min_investment: 5000000,
    timeline_months: 24,
    expected_return: 6400000,
    status: "open",
  },
  {
    id: "inv-2",
    title: "Marina Heights Shortlet Fund, Lagos",
    description:
      "Pooled investment in a portfolio of 10 premium shortlet apartments on Victoria Island, targeting consistent quarterly payouts.",
    image_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80",
    roi_estimate_percent: 19,
    min_investment: 2000000,
    timeline_months: 18,
    expected_return: 2380000,
    status: "open",
  },
  {
    id: "inv-3",
    title: "Diplomatic Drive Commercial Plaza",
    description:
      "Ground-floor retail and office plaza in Abuja's diplomatic zone, fully pre-leased to anchor tenants ahead of completion.",
    image_url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80",
    roi_estimate_percent: 22,
    min_investment: 10000000,
    timeline_months: 30,
    expected_return: 12200000,
    status: "open",
  },
];

export const CITIES = ["Abuja", "Lagos", "Dubai", "Port Harcourt", "Kano", "Ibadan"];

export const MOCK_AGENTS = Array.from(
  new Map(
    MOCK_PROPERTIES.filter((p) => p.agent).map((p) => [p.agent!.id, p.agent!])
  ).values()
);
